/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package insert_items;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import home_food_software.selection;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author isuru udana
 */
public class insert extends javax.swing.JFrame {
Connection conn,conn2= null;
    PreparedStatement pre,pre1 =null;
         static  int what;
    /**
     * Creates new form insert
     */
    public insert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent_panal_insert = new javax.swing.JPanel();
        step1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        step2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        step3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        step4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1140, 620));

        parent_panal_insert.setPreferredSize(new java.awt.Dimension(1140, 620));
        parent_panal_insert.setLayout(new java.awt.CardLayout());

        step1.setBackground(new java.awt.Color(204, 204, 255));
        step1.setMaximumSize(new java.awt.Dimension(1140, 620));
        step1.setPreferredSize(new java.awt.Dimension(1140, 620));
        step1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel1.setText("Step1");
        step1.add(jLabel1);
        jLabel1.setBounds(150, 10, 64, 29);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rice category", "Vegitabale category", "Meat & fish category", "Dessert category" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        step1.add(jComboBox1);
        jComboBox1.setBounds(580, 100, 145, 22);

        jLabel5.setText("Selet the catogery:");
        step1.add(jLabel5);
        jLabel5.setBounds(390, 100, 129, 16);

        jLabel6.setText("Insert ID:");
        step1.add(jLabel6);
        jLabel6.setBounds(450, 150, 54, 16);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        step1.add(jTextField1);
        jTextField1.setBounds(580, 150, 145, 22);

        jLabel7.setText("Insert Name:");
        step1.add(jLabel7);
        jLabel7.setBounds(430, 200, 75, 16);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        step1.add(jTextField2);
        jTextField2.setBounds(580, 200, 145, 22);

        jButton1.setText("OK");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        step1.add(jButton1);
        jButton1.setBounds(770, 290, 220, 60);

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Insert ID and Name");
        step1.add(jLabel24);
        jLabel24.setBounds(480, 10, 213, 29);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insert_items/bg_3.jpg"))); // NOI18N
        jLabel42.setMaximumSize(new java.awt.Dimension(1140, 620));
        jLabel42.setMinimumSize(new java.awt.Dimension(1140, 620));
        step1.add(jLabel42);
        jLabel42.setBounds(1, 0, 1140, 620);

        parent_panal_insert.add(step1, "card5");

        step2.setBackground(new java.awt.Color(204, 204, 255));
        step2.setPreferredSize(new java.awt.Dimension(1140, 620));
        step2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel2.setText("Step2");
        step2.add(jLabel2);
        jLabel2.setBounds(150, 10, 64, 29);

        jButton2.setText("OK");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        step2.add(jButton2);
        jButton2.setBounds(840, 460, 220, 60);

        jLabel8.setText("calcium ");
        step2.add(jLabel8);
        jLabel8.setBounds(330, 70, 47, 16);

        jLabel9.setText("chloride");
        step2.add(jLabel9);
        jLabel9.setBounds(330, 120, 45, 16);

        jLabel10.setText("chromium");
        step2.add(jLabel10);
        jLabel10.setBounds(330, 170, 57, 16);

        jLabel11.setText("copper ");
        step2.add(jLabel11);
        jLabel11.setBounds(330, 220, 43, 16);

        jLabel12.setText("fluoride");
        step2.add(jLabel12);
        jLabel12.setBounds(330, 290, 43, 16);

        jLabel13.setText("Iodine ");
        step2.add(jLabel13);
        jLabel13.setBounds(330, 340, 39, 10);

        jLabel14.setText("iron");
        step2.add(jLabel14);
        jLabel14.setBounds(330, 400, 22, 16);

        jLabel15.setText("sodium");
        step2.add(jLabel15);
        jLabel15.setBounds(670, 400, 51, 16);

        jLabel16.setText("magnesium");
        step2.add(jLabel16);
        jLabel16.setBounds(670, 70, 80, 30);

        jLabel17.setText("molybdenum");
        step2.add(jLabel17);
        jLabel17.setBounds(670, 130, 73, 16);

        jLabel18.setText("phosphorus ");
        step2.add(jLabel18);
        jLabel18.setBounds(670, 170, 70, 16);

        jLabel19.setText("potassium");
        step2.add(jLabel19);
        jLabel19.setBounds(670, 220, 58, 16);

        jLabel20.setText("selenium");
        step2.add(jLabel20);
        jLabel20.setBounds(670, 280, 51, 16);

        jLabel21.setText("zinc ");
        step2.add(jLabel21);
        jLabel21.setBounds(680, 340, 26, 16);

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel23.setText("Enter the Minerals");
        step2.add(jLabel23);
        jLabel23.setBounds(480, 20, 210, 29);
        step2.add(jTextField3);
        jTextField3.setBounds(420, 390, 100, 22);
        step2.add(jTextField4);
        jTextField4.setBounds(420, 70, 100, 22);
        step2.add(jTextField5);
        jTextField5.setBounds(420, 120, 100, 22);
        step2.add(jTextField6);
        jTextField6.setBounds(420, 170, 100, 22);
        step2.add(jTextField7);
        jTextField7.setBounds(420, 220, 100, 22);
        step2.add(jTextField8);
        jTextField8.setBounds(420, 280, 100, 22);
        step2.add(jTextField9);
        jTextField9.setBounds(420, 330, 100, 22);
        step2.add(jTextField10);
        jTextField10.setBounds(780, 400, 101, 22);
        step2.add(jTextField11);
        jTextField11.setBounds(780, 280, 101, 22);
        step2.add(jTextField12);
        jTextField12.setBounds(780, 120, 100, 22);
        step2.add(jTextField13);
        jTextField13.setBounds(780, 170, 100, 22);
        step2.add(jTextField14);
        jTextField14.setBounds(780, 220, 100, 22);
        step2.add(jTextField15);
        jTextField15.setBounds(780, 70, 100, 22);
        step2.add(jTextField16);
        jTextField16.setBounds(780, 330, 101, 22);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insert_items/bg_3.jpg"))); // NOI18N
        jLabel43.setMaximumSize(new java.awt.Dimension(1140, 620));
        jLabel43.setMinimumSize(new java.awt.Dimension(1140, 620));
        jLabel43.setPreferredSize(new java.awt.Dimension(1140, 620));
        step2.add(jLabel43);
        jLabel43.setBounds(1, 0, 1140, 620);

        parent_panal_insert.add(step2, "card4");

        step3.setBackground(new java.awt.Color(204, 204, 255));
        step3.setPreferredSize(new java.awt.Dimension(1140, 620));
        step3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel3.setText("Step3");
        step3.add(jLabel3);
        jLabel3.setBounds(150, 10, 64, 29);

        jButton3.setText("OK");
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        step3.add(jButton3);
        jButton3.setBounds(590, 260, 220, 60);

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel22.setText("Enter the Nutrition");
        step3.add(jLabel22);
        jLabel22.setBounds(480, 10, 218, 29);

        jLabel25.setText("protien ");
        step3.add(jLabel25);
        jLabel25.setBounds(330, 70, 44, 16);

        jLabel26.setText("carbohydrate");
        step3.add(jLabel26);
        jLabel26.setBounds(330, 130, 75, 16);

        jLabel27.setText("fat ");
        step3.add(jLabel27);
        jLabel27.setBounds(330, 190, 19, 16);
        step3.add(jTextField17);
        jTextField17.setBounds(420, 70, 100, 22);
        step3.add(jTextField18);
        jTextField18.setBounds(420, 130, 101, 22);
        step3.add(jTextField19);
        jTextField19.setBounds(420, 190, 101, 22);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insert_items/bg_3.jpg"))); // NOI18N
        step3.add(jLabel44);
        jLabel44.setBounds(1, 1, 1140, 620);

        parent_panal_insert.add(step3, "card3");

        step4.setBackground(new java.awt.Color(204, 204, 255));
        step4.setPreferredSize(new java.awt.Dimension(1140, 620));
        step4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel4.setText("Step4");
        step4.add(jLabel4);
        jLabel4.setBounds(150, 10, 64, 29);

        jButton4.setText("OK");
        jButton4.setBorder(new javax.swing.border.MatteBorder(null));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        step4.add(jButton4);
        jButton4.setBounds(810, 440, 220, 60);

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel28.setText("Enter the Vitamins");
        step4.add(jLabel28);
        jLabel28.setBounds(480, 20, 214, 29);

        jLabel29.setText("Vitamin_A ");
        step4.add(jLabel29);
        jLabel29.setBounds(290, 80, 62, 16);

        jLabel30.setText("Thiamin");
        step4.add(jLabel30);
        jLabel30.setBounds(290, 120, 46, 16);

        jLabel31.setText("Ribloflevin ");
        step4.add(jLabel31);
        jLabel31.setBounds(290, 170, 62, 16);

        jLabel32.setText(" niacin");
        step4.add(jLabel32);
        jLabel32.setBounds(290, 220, 67, 16);

        jLabel33.setText("pantothenic");
        step4.add(jLabel33);
        jLabel33.setBounds(290, 280, 66, 16);

        jLabel34.setText("biotin ");
        step4.add(jLabel34);
        jLabel34.setBounds(290, 340, 35, 16);

        jLabel35.setText("piridoxine");
        step4.add(jLabel35);
        jLabel35.setBounds(290, 390, 55, 16);

        jLabel36.setText("vitamin_B12");
        step4.add(jLabel36);
        jLabel36.setBounds(630, 70, 69, 16);

        jLabel37.setText("folic_acid");
        step4.add(jLabel37);
        jLabel37.setBounds(640, 120, 53, 16);

        jLabel38.setText("Vitamin_C");
        step4.add(jLabel38);
        jLabel38.setBounds(640, 170, 58, 16);

        jLabel39.setText("Vitamin_D");
        step4.add(jLabel39);
        jLabel39.setBounds(630, 220, 58, 16);

        jLabel40.setText("vitamin_E ");
        step4.add(jLabel40);
        jLabel40.setBounds(630, 290, 59, 16);

        jLabel41.setText("vitamin_k ");
        step4.add(jLabel41);
        jLabel41.setBounds(630, 340, 58, 16);

        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        step4.add(jTextField20);
        jTextField20.setBounds(420, 70, 100, 22);
        step4.add(jTextField21);
        jTextField21.setBounds(420, 120, 100, 22);
        step4.add(jTextField22);
        jTextField22.setBounds(420, 170, 100, 22);
        step4.add(jTextField23);
        jTextField23.setBounds(420, 220, 100, 22);
        step4.add(jTextField24);
        jTextField24.setBounds(420, 280, 100, 22);

        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });
        step4.add(jTextField25);
        jTextField25.setBounds(420, 330, 100, 22);
        step4.add(jTextField26);
        jTextField26.setBounds(420, 390, 100, 22);

        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });
        step4.add(jTextField27);
        jTextField27.setBounds(780, 70, 100, 22);
        step4.add(jTextField28);
        jTextField28.setBounds(780, 120, 100, 22);
        step4.add(jTextField29);
        jTextField29.setBounds(780, 170, 100, 22);
        step4.add(jTextField30);
        jTextField30.setBounds(780, 220, 100, 22);
        step4.add(jTextField31);
        jTextField31.setBounds(780, 280, 100, 22);
        step4.add(jTextField32);
        jTextField32.setBounds(780, 330, 100, 22);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insert_items/bg_3.jpg"))); // NOI18N
        step4.add(jLabel45);
        jLabel45.setBounds(1, 0, 1140, 620);

        parent_panal_insert.add(step4, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(parent_panal_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(parent_panal_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
  

       String catogary= (String)jComboBox1.getSelectedItem();
  
       if(catogary=="Rice category"){ rs = find_r(jTextField1.getText());   
         try{
            if(rs.next()){
                JOptionPane.showMessageDialog(null, " This ID is available");}
            else{
                what=1;
                String j=""+jTextField2.getText()+"";
                insert1(jTextField1.getText() ,j);
                movingpanals();
            }
         
         
         }
       catch(Exception ex){}
       
       
       }
      if(catogary=="Vegitabale category"){rs1 = find_v(jTextField1.getText());
        
         try{
            if(rs1.next()){
                JOptionPane.showMessageDialog(null, " This ID is available");}
            else{what=2;
            String j=""+jTextField2.getText()+"";
                insert1(jTextField1.getText() ,j);
                movingpanals();}
         
         
         }
       catch(Exception ex){}
      }
      if(catogary=="Meat & fish category"){rs2 = find_m(jTextField1.getText());
        
         try{
            if(rs2.next()){
                JOptionPane.showMessageDialog(null, " This ID is available");}
            else{
               
                what=3;
            String j=""+jTextField2.getText()+"";
            insert1(jTextField1.getText(),j);
             movingpanals();}
         
         
         }
       catch(Exception ex){}
      
      }
         if(catogary=="Dessert category"){rs3= find_d(jTextField1.getText());
           
         try{
            if(rs3.next()){ 
                JOptionPane.showMessageDialog(null, " This ID is available");}
            else{what=4;
            String j=""+jTextField2.getText()+"";
           insert1(jTextField1.getText() ,j);
                movingpanals();}
        
         
         }
       catch(Exception ex){}}
      
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String m1= jTextField3.getText(),m2=jTextField4.getText(),m3=jTextField5.getText(),m4=jTextField6.getText(),m5=jTextField7.getText()
                ,m6=jTextField8.getText(),m7=jTextField9.getText(),m8=jTextField10.getText(),m9=jTextField11.getText(),m10=jTextField12.getText(),
                m11=jTextField13.getText(),m12=jTextField14.getText(),m13=jTextField15.getText(),m14=jTextField16.getText();
           String id=  jTextField1.getText();       
          insert_minarls(id,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14);
        movingpanals2();
             
  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String n1=jTextField17.getText(),n2=jTextField18.getText(),n3=jTextField19.getText();
         String id=  jTextField1.getText(); 
         System.out.println(id);
        insert_nutrition(id,n1,n2,n3);
         movingpanals3();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            String v1= jTextField20.getText(),v2=jTextField21.getText(),v3=jTextField22.getText(),v4=jTextField23.getText(),v5=jTextField24.getText()
                ,v6=jTextField25.getText(),v7=jTextField26.getText(),v8=jTextField27.getText(),v9=jTextField28.getText(),v10=jTextField29.getText(),
                v11=jTextField30.getText(),v12=jTextField31.getText(),v13=jTextField32.getText();
           String id=  jTextField1.getText();       
          insert_vitamin(id,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13);
          JOptionPane.showMessageDialog(rootPane, "You enter item  :"+jTextField2.getText()+" sussfully!   item id :"+jTextField1.getText()+"");
                                            
           String[] args = null;
selection.selectionmain(args);
     close();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void insert_main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel parent_panal_insert;
    private javax.swing.JPanel step1;
    private javax.swing.JPanel step2;
    private javax.swing.JPanel step3;
    private javax.swing.JPanel step4;
    // End of variables declaration//GEN-END:variables





  ResultSet rs = null;
    ResultSet rs1 = null;
         ResultSet rs2 = null;
          ResultSet rs3 = null;
PreparedStatement ps = null;
    
 public ResultSet find_r(String s){
      
           try{ 
          conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/online_food_order","root","");
           ps = (PreparedStatement) conn.prepareStatement("select * from rice_varieties where RiceId = ?");
           ps.setString(1,s);
           rs = ps.executeQuery();
           }catch(SQLException ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
           }
           return rs;

       }
  public ResultSet find_v(String s){
           try{
          conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/online_food_order","root","");
           ps = (PreparedStatement) conn.prepareStatement("select * from vegetables where VegetableId = ?");
           ps.setString(1,s);
           rs1 = ps.executeQuery();
           }catch(SQLException ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
           }
           return rs1;

       }
  public ResultSet find_m(String s){
           try{
          conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/online_food_order","root","");
           ps = (PreparedStatement) conn.prepareStatement("select * from meat_and_fish where Meat_or_FishId = ?");
           ps.setString(1,s);
           rs2= ps.executeQuery();
           }catch(Exception ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
           }
           return rs2;

       }
  public ResultSet find_d(String s){
           try{
          conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/online_food_order","root","");
           ps = (PreparedStatement) conn.prepareStatement("select * from dessert where DessertId = ?");
           ps.setString(1,s);
           rs3 = ps.executeQuery();
           }catch(Exception ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
           }
           return rs3;

       }

 
 public void movingpanals(){
    parent_panal_insert.removeAll();
        parent_panal_insert.add(step2);
        parent_panal_insert.repaint();
        parent_panal_insert.revalidate();
      } 
public void movingpanals2(){
    parent_panal_insert.removeAll();
        parent_panal_insert.add(step3);
        parent_panal_insert.repaint();
        parent_panal_insert.revalidate();
      }   
public void movingpanals3(){
    parent_panal_insert.removeAll();
        parent_panal_insert.add(step4);
        parent_panal_insert.repaint();
        parent_panal_insert.revalidate();
      }   

public void insert1(String s,String k){   
                
             
     try {
         String sq4 = null;
        
           
         
         if(what==1)   {sq4="INSERT INTO rice_varieties"+"(RiceId,Name_of_the_Rice)"+ "VALUES (?,?)" ; }
            
        if(what==2){ sq4="INSERT INTO vegetables"+"(VegetableId,Name_of_the_Vegetable)"+ "VALUES (?,?)" ; }
         if(what==3){ sq4="INSERT INTO meat_and_fish"+"(Meat_or_FishId,Name_of_the_Meat_or_Fish)"+ "VALUES (?,?)";   }
         
         
         if(what==4){     sq4="INSERT INTO dessert"+"(DessertId,Name_of_the_Dessert)"+ "VALUES (?,?)";
        
         }
           conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/online_food_order","root","");
           pre=(PreparedStatement) conn.prepareStatement(sq4);
          pre.setString(1,s);
          pre.setString(2, k);
          pre.executeUpdate();
        
        }
       catch(Exception ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
        }
  
  
 
  } 

public void insert_minarls(String id,String m1,String m2,String m3,String m4,String m5,String m6,String m7,String m8,String m9,String m10,String m11,String m12,String m13,String m14){
    try {
    String sq5 = null;
    if(what==1){ sq5="INSERT INTO `content_minarals_for_rice`(`RiceId`, `calcium`, `chloride`, `chromium`, `copper`, `fluoride`, `Iodine`, `iron`, `magnesium`, `molybdenum`, `phosphorus`, `potassium`, `selenium`, `znc`, `sodium`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";}
  if(what==2){ sq5="INSERT INTO `content_minarals_for_vegetables`(`vegetableId`, `calcium`, `chloride`, `chromium`, `copper`, `fluoride`, `Iodine`, `iron`, `magnesium`, `molybdenum`, `phosphorus`, `potassium`, `selenium`, `znc`, `sodium`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";}
  if(what==3){ sq5="INSERT INTO `content_minarals_for_meat_and_fish`(`meat_and_fishId`, `calcium`, `chloride`, `chromium`, `copper`, `fluoride`, `Iodine`, `iron`, `magnesium`, `molybdenum`, `phosphorus`, `potassium`, `selenium`, `znc`, `sodium`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";}
  if(what==4){ sq5="INSERT INTO `content_minarals_for_dessert`(`dessertId`, `calcium`, `chloride`, `chromium`, `copper`, `fluoride`, `Iodine`, `iron`, `magnesium`, `molybdenum`, `phosphorus`, `potassium`, `selenium`, `znc`, `sodium`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";}
    
    conn2= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/online_food_order","root","");
           pre=(PreparedStatement) conn.prepareStatement(sq5);
          pre.setString(1,id);
           pre.setString(2, m1);
            pre.setString(3,m2);
           pre.setString(4, m3);
            pre.setString(5,m4);
           pre.setString(6, m5);
            pre.setString(7,m6);
           pre.setString(8, m7);
            pre.setString(9,m8);
           pre.setString(10, m9);
            pre.setString(11,m10);
           pre.setString(12, m11);
            pre.setString(13,m12);
           pre.setString(14, m13);
           pre.setString(15, m14);
           pre.executeUpdate();
    
    
    
    } catch(Exception ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
        }
 }


public void insert_nutrition(String id,String n1,String n2,String n3){
  try {String sq4=null;
    if(what==1){   sq4="INSERT INTO `content_nutrition_for_rice`(`RiceId`, `protien`, `carbohydrate`, `fat`) VALUES (?,?,?,?)";}
    if(what==2){  sq4="INSERT INTO `content_nutrition_for_vegetables`(`vegitableId`, `protien`, `carbohydrate`, `fat`) VALUES (?,?,?,?)";}
    if(what==3){   sq4="INSERT INTO `content_nutrition_for_meat_and_fish`(`meat_and_fishId`, `protien`, `carbohydrate`, `fat`) VALUES  (?,?,?,?)";}
    if(what==4){   sq4="INSERT INTO `content_nutrition_for_dessert`(`dessertId`, `protien`, `carbohydrate`, `fat`) VALUES  (?,?,?,?)";}
      pre=(PreparedStatement) conn.prepareStatement(sq4);
      
          pre.setString(1,id);
           pre.setString(2, n1);
            pre.setString(3,n2);
           pre.setString(4, n3);
          pre.executeUpdate();
      
      
  }catch(Exception ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
        }
  }
  
  

public void insert_vitamin(String id,String v1,String v2,String v3,String v4,String v5,String v6,String v7,String v8,String v9,String v10,String v11,String v12,String v13){
  try {
     
      String sq4=null;
      if(what==1){ sq4="INSERT INTO `content_vitamins_in_rice`(`RiceId`, `Vitamin_A`, `Thiamin`, `Ribloflevin`, `niacin`, `pantothenic`, `biotin`, `piridoxine`, `vitamin_B12`, `folic_acid`, `Vitamin_C`, `Vitamin_D`, `vitamin_E`, `vitamin_k`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";}
      if(what==2){sq4="INSERT INTO `content_vitamins_in_vegetables`(`vegetableId`, `Vitamin_A`, `Thiamin`, `Ribloflevin`, `niacin`, `pantothenic`, `biotin`, `piridoxine`, `vitamin_B12`, `folic_acid`, `Vitamin_C`, `Vitamin_D`, `vitamin_E`, `vitamin_k`)  VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";}
      if(what==3){sq4="INSERT INTO `content_vitamins_in_meat_and_fish`(`meat_and_fishId`, `Vitamin_A`, `Thiamin`, `Ribloflevin`, `niacin`, `pantothenic`, `biotin`, `piridoxine`, `vitamin_B12`, `folic_acid`, `Vitamin_C`, `Vitamin_D`, `vitamin_E`, `vitamin_k`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";}
      if(what==4){sq4="INSERT INTO `content_vitamins_in_dessert`(`dessertId`, `Vitamin_A`, `Thiamin`, `Ribloflevin`, `niacin`, `pantothenic`, `biotin`, `piridoxine`, `vitamin_B12`, `folic_acid`, `Vitamin_C`, `Vitamin_D`, `vitamin_E`, `vitamin_k`) VALUES  (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";}
          
      
      pre=(PreparedStatement) conn.prepareStatement(sq4);
      
          pre.setString(1,id);
           pre.setString(2, v1);
            pre.setString(3,v2);
           pre.setString(4, v3);
           pre.setString(5, v4);
            pre.setString(6,v5);
           pre.setString(7, v6);
           pre.setString(8,v7);
           pre.setString(9, v8);
            pre.setString(10,v9);
           pre.setString(11, v10);
           pre.setString(12, v11);
            pre.setString(13,v12);
           pre.setString(14, v13);
          pre.executeUpdate();
      
      
  }catch(Exception ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
        }
  }


public  void close(){
WindowEvent windowClose= new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowClose);
}

}
