/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package delete_items;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author isuru udana
 */
public class delete_rice1 extends javax.swing.JFrame {
 public static int rownumber=0;
    Connection conn= null;
    PreparedStatement pre =null;
    static int what;
    /**
     * Creates new form delete_rice1
     */
    public delete_rice1() {
        initComponents();
    }
 public  void close(){
WindowEvent windowClose= new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowClose);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent_panel = new javax.swing.JPanel();
        insert_id = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comforming = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        parent_panel.setMaximumSize(new java.awt.Dimension(626, 352));
        parent_panel.setPreferredSize(new java.awt.Dimension(630, 280));
        parent_panel.setLayout(new java.awt.CardLayout());

        insert_id.setBackground(new java.awt.Color(204, 204, 255));
        insert_id.setMaximumSize(new java.awt.Dimension(588, 264));
        insert_id.setPreferredSize(new java.awt.Dimension(630, 280));
        insert_id.setLayout(null);

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        insert_id.add(jButton3);
        jButton3.setBounds(130, 160, 72, 25);

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        insert_id.add(jButton4);
        jButton4.setBounds(280, 160, 71, 25);

        jLabel1.setText("Insert the ID:");
        insert_id.add(jLabel1);
        jLabel1.setBounds(126, 108, 76, 16);

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        insert_id.add(ID);
        ID.setBounds(269, 105, 158, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Deleting a item");
        insert_id.add(jLabel2);
        jLabel2.setBounds(194, 13, 161, 33);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rice category", "Vegitabale category", "Meat & fish category", "Dessert category", " " }));
        insert_id.add(jComboBox1);
        jComboBox1.setBounds(269, 53, 158, 22);

        jLabel5.setText("Selet the catogery:");
        insert_id.add(jLabel5);
        jLabel5.setBounds(93, 53, 109, 16);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_items/myfood.jpg"))); // NOI18N
        insert_id.add(jLabel7);
        jLabel7.setBounds(0, 0, 660, 280);

        parent_panel.add(insert_id, "card2");

        comforming.setBackground(new java.awt.Color(204, 204, 255));
        comforming.setMaximumSize(new java.awt.Dimension(626, 352));
        comforming.setPreferredSize(new java.awt.Dimension(630, 280));
        comforming.setLayout(null);

        jButton1.setText("OK");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        comforming.add(jButton1);
        jButton1.setBounds(30, 130, 130, 50);

        jButton2.setText("Cancel");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        comforming.add(jButton2);
        jButton2.setBounds(180, 130, 130, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Are you sure you wont to permanenty delete this rice.");
        comforming.add(jLabel3);
        jLabel3.setBounds(10, 50, 355, 16);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("It is going to delete all data about this item.");
        comforming.add(jLabel4);
        jLabel4.setBounds(10, 70, 326, 16);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_items/myfood.jpg"))); // NOI18N
        comforming.add(jLabel8);
        jLabel8.setBounds(0, 0, 640, 280);

        parent_panel.add(comforming, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(parent_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(parent_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
     String select_catogary=(String)jComboBox1.getSelectedItem();
     
     try{
         if(select_catogary=="Rice category"){
          find_r(ID.getText());
         if(rs.next()){
           movingpanals();
           what=1;
            System.out.print(what);
          }
         else {
          JOptionPane.showMessageDialog(null, "NO DATA FOR THIS ID");
      }
         
         }
      
     else if(select_catogary=="Vegitabale category"){
         find_v(ID.getText());
         if(rs1.next()){
           movingpanals();
            what=2;
            System.out.print(what); 
      }
     else {
          JOptionPane.showMessageDialog(null, "NO DATA FOR THIS ID");
      }
     }
      
   else if(select_catogary=="Meat & fish category"){
       find_m(ID.getText());
       if(rs2.next()){
          movingpanals();
          what=3;
          System.out.print(what);
      }
       else {
          JOptionPane.showMessageDialog(null, "NO DATA FOR THIS ID");
      }
   }
   else if(select_catogary=="Dessert category"){
        find_d(ID.getText());
       if(rs3.next()){
        movingpanals();
        what=4;
        System.out.print(what);
      }
   else {
          JOptionPane.showMessageDialog(null, "NO DATA FOR THIS ID");
      }
   }
      
        
    }catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        delete(ID.getText());
     
       close();   
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void delete_rice1_main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete_rice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete_rice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete_rice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete_rice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delete_rice1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JPanel comforming;
    private javax.swing.JPanel insert_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel parent_panel;
    // End of variables declaration//GEN-END:variables







 Connection con = null;
       ResultSet rs = null;
        ResultSet rs1 = null;
         ResultSet rs2 = null;
          ResultSet rs3 = null;
       PreparedStatement ps = null;
       
       public ResultSet find_r(String s){
           try{
          conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/online_food_order","root","");
           ps = (PreparedStatement) conn.prepareStatement("select * from rice_varieties where RiceId = ?");
           ps.setString(1,s);
           rs = ps.executeQuery();
           }catch(SQLException ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
           }
           return rs;

       }
 public ResultSet find_v(String s){
           try{
          conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/online_food_order","root","");
           ps = (PreparedStatement) conn.prepareStatement("select * from vegetables where VegetableId = ?");
           ps.setString(1,s);
           rs1 = ps.executeQuery();
           }catch(SQLException ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
           }
           return rs1;

       }
  public ResultSet find_m(String s){
           try{
          conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/online_food_order","root","");
           ps = (PreparedStatement) conn.prepareStatement("select * from meat_and_fish where Meat_or_FishId = ?");
           ps.setString(1,s);
           rs2= ps.executeQuery();
           }catch(Exception ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
           }
           return rs2;

       }
  public ResultSet find_d(String s){
           try{
          conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/online_food_order","root","");
           ps = (PreparedStatement) conn.prepareStatement("select * from dessert where DessertId = ?");
           ps.setString(1,s);
           rs3 = ps.executeQuery();
           }catch(Exception ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
           }
           return rs3;

       }

  public void delete(String s){   
                
                
              
     try {
         String sq4=null,sq5=null,sq6=null,sq7= null;
         
           
         
         if(what==1)   { sq4="DELETE FROM `rice_varieties` WHERE `RiceId` =?" ;
           sq5="DELETE FROM `content_minarals_for_rice` WHERE `RiceId` =?";
           sq6="DELETE FROM `content_nutrition_for_rice` WHERE `RiceId` =?";
           sq7="DELETE FROM `content_vitamins_in_rice` WHERE `RiceId` =? ";
         
         
         }
                 
            
        if(what==2){ sq4="DELETE FROM `vegetables` WHERE `VegetableId` =?" ;
        sq5="DELETE FROM `content_minarals_for_vegetables` WHERE `VegetableId` =?";
           sq6="DELETE FROM `content_nutrition_for_vegetables` WHERE `VegetableId` =?";
           sq7="DELETE FROM `content_vitamins_in_vegetables` WHERE `VegetableId` =? ";}

        
        
        if(what==3){ sq4="DELETE FROM `meat_and_fish` WHERE `Meat_or_FishId` =?" ;
           sq5="DELETE FROM `content_minarals_for_meat_and_fish` WHERE `Meat_or_FishId` =?";
           sq6="DELETE FROM `content_nutrition_for_meat_and_fish` WHERE `Meat_or_FishId` =?";
           sq7="DELETE FROM `content_vitamins_in_meat_and_fish` WHERE `Meat_or_FishId` =? ";}
        
        
        
         if(what==4){     sq4="DELETE FROM `dessert` WHERE `DessertId` =?" ;
         sq5="DELETE FROM `content_minarals_for_dessert` WHERE `DessertId` =?";
           sq6="DELETE FROM `content_nutrition_for_dessert` WHERE `DessertId` =?";
           sq7="DELETE FROM `content_vitamins_in_dessert` WHERE `DessertId` =? ";}
         
         
           conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/online_food_order","root","");
           pre=(PreparedStatement) conn.prepareStatement(sq4);
         pre.setString(1,s);
           pre.executeUpdate();
           pre=(PreparedStatement) conn.prepareStatement(sq5);
         pre.setString(1,s);
           pre.executeUpdate();
           pre=(PreparedStatement) conn.prepareStatement(sq6);
         pre.setString(1,s);
           pre.executeUpdate();
           pre=(PreparedStatement) conn.prepareStatement(sq7);
         pre.setString(1,s);
           pre.executeUpdate();
        
         
         }
        catch (SQLException |HeadlessException ex ) {
            JOptionPane.showMessageDialog(null,ex);
        }
  
  
  JOptionPane.showMessageDialog(null,"Delete success!!!");
  } 
             
           
      public void movingpanals(){
      parent_panel.removeAll();
        parent_panel.add(comforming);
        parent_panel.repaint();
        parent_panel.revalidate();
      
      }        
           
          
  }  







