/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package change_items;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import home_food_software.selection;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author isuru udana
 */
public class change extends javax.swing.JFrame {
    Connection conn,conn2= null;
    PreparedStatement pre,pre1 =null;
         static  int what;

    /**
     * Creates new form change
     */
    public change() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent_panal_change = new javax.swing.JPanel();
        step1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        step2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        step3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        step4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        parent_panal_change.setLayout(new java.awt.CardLayout());

        step1.setBackground(new java.awt.Color(255, 153, 0));
        step1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel1.setText("Step1");
        step1.add(jLabel1);
        jLabel1.setBounds(12, 13, 64, 29);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel5.setText("Insert ID and Name");
        step1.add(jLabel5);
        jLabel5.setBounds(270, 20, 213, 29);

        jLabel6.setText("Selet the catogery:");
        step1.add(jLabel6);
        jLabel6.setBounds(140, 120, 109, 16);

        jLabel7.setText("Insert ID:");
        step1.add(jLabel7);
        jLabel7.setBounds(180, 180, 54, 16);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        step1.add(jTextField2);
        jTextField2.setBounds(278, 174, 270, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rice category", "Vegitabale category", "Meat & fish category", "Dessert category", " " }));
        step1.add(jComboBox1);
        jComboBox1.setBounds(278, 111, 270, 40);

        jButton1.setText("OK");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        step1.add(jButton1);
        jButton1.setBounds(430, 250, 220, 60);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/change_items/bg_3.jpg"))); // NOI18N
        step1.add(jLabel42);
        jLabel42.setBounds(-830, -380, 1650, 960);

        parent_panal_change.add(step1, "card2");

        step2.setBackground(new java.awt.Color(255, 153, 0));
        step2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel2.setText("Step2");
        step2.add(jLabel2);
        jLabel2.setBounds(12, 13, 64, 29);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel9.setText("Enter the changing Minerals");
        step2.add(jLabel9);
        jLabel9.setBounds(270, 20, 316, 29);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        step2.add(jTextField1);
        jTextField1.setBounds(320, 120, 103, 22);
        step2.add(jTextField3);
        jTextField3.setBounds(320, 160, 103, 22);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        step2.add(jTextField4);
        jTextField4.setBounds(320, 200, 103, 22);
        step2.add(jTextField5);
        jTextField5.setBounds(320, 240, 103, 22);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        step2.add(jTextField6);
        jTextField6.setBounds(320, 280, 103, 22);
        step2.add(jTextField7);
        jTextField7.setBounds(320, 320, 103, 22);
        step2.add(jTextField8);
        jTextField8.setBounds(320, 360, 103, 22);

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        step2.add(jTextField9);
        jTextField9.setBounds(600, 120, 103, 22);
        step2.add(jTextField10);
        jTextField10.setBounds(600, 160, 103, 22);
        step2.add(jTextField11);
        jTextField11.setBounds(600, 200, 103, 22);
        step2.add(jTextField12);
        jTextField12.setBounds(600, 250, 103, 22);

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        step2.add(jTextField13);
        jTextField13.setBounds(600, 290, 103, 22);

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        step2.add(jTextField14);
        jTextField14.setBounds(600, 330, 103, 22);
        step2.add(jTextField15);
        jTextField15.setBounds(600, 370, 103, 22);

        jLabel10.setText("calcium ");
        step2.add(jLabel10);
        jLabel10.setBounds(220, 120, 70, 16);

        jLabel11.setText("chloride");
        step2.add(jLabel11);
        jLabel11.setBounds(220, 170, 45, 16);

        jLabel12.setText("chromium");
        step2.add(jLabel12);
        jLabel12.setBounds(220, 210, 57, 16);

        jLabel13.setText("copper ");
        step2.add(jLabel13);
        jLabel13.setBounds(220, 250, 43, 16);

        jLabel14.setText("fluoride");
        step2.add(jLabel14);
        jLabel14.setBounds(220, 280, 43, 16);

        jLabel15.setText("Iodine ");
        step2.add(jLabel15);
        jLabel15.setBounds(220, 320, 39, 16);

        jLabel16.setText("iron");
        step2.add(jLabel16);
        jLabel16.setBounds(220, 360, 22, 16);

        jLabel17.setText("magnesium");
        step2.add(jLabel17);
        jLabel17.setBounds(500, 120, 66, 16);

        jLabel18.setText("molybdenum");
        step2.add(jLabel18);
        jLabel18.setBounds(500, 160, 73, 16);

        jLabel19.setText("phosphorus ");
        step2.add(jLabel19);
        jLabel19.setBounds(500, 200, 70, 16);

        jLabel20.setText("potassium");
        step2.add(jLabel20);
        jLabel20.setBounds(500, 250, 58, 16);

        jLabel21.setText("selenium");
        step2.add(jLabel21);
        jLabel21.setBounds(500, 290, 51, 16);

        jLabel22.setText("zinc ");
        step2.add(jLabel22);
        jLabel22.setBounds(500, 330, 26, 16);

        jLabel23.setText("sodium");
        step2.add(jLabel23);
        jLabel23.setBounds(500, 370, 41, 16);

        jButton2.setText("OK");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        step2.add(jButton2);
        jButton2.setBounds(550, 420, 220, 60);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/change_items/bg_3.jpg"))); // NOI18N
        step2.add(jLabel43);
        jLabel43.setBounds(-830, -380, 1650, 960);

        parent_panal_change.add(step2, "card3");

        step3.setBackground(new java.awt.Color(255, 153, 0));
        step3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel3.setText("Step3");
        step3.add(jLabel3);
        jLabel3.setBounds(12, 13, 64, 29);

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel24.setText("Enter the changine Nutrition");
        step3.add(jLabel24);
        jLabel24.setBounds(270, 20, 324, 29);
        jLabel24.getAccessibleContext().setAccessibleDescription("");

        jLabel25.setText("protien ");
        step3.add(jLabel25);
        jLabel25.setBounds(175, 124, 44, 16);

        jLabel26.setText("carbohydrate");
        step3.add(jLabel26);
        jLabel26.setBounds(175, 164, 75, 16);

        jLabel27.setText("fat ");
        step3.add(jLabel27);
        jLabel27.setBounds(175, 204, 19, 16);
        step3.add(jTextField16);
        jTextField16.setBounds(273, 121, 111, 22);

        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        step3.add(jTextField17);
        jTextField17.setBounds(273, 161, 111, 22);
        step3.add(jTextField18);
        jTextField18.setBounds(273, 201, 111, 22);

        jButton3.setText("OK");
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        step3.add(jButton3);
        jButton3.setBounds(470, 260, 220, 60);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/change_items/bg_3.jpg"))); // NOI18N
        step3.add(jLabel44);
        jLabel44.setBounds(-830, -380, 1650, 960);

        parent_panal_change.add(step3, "card4");

        step4.setBackground(new java.awt.Color(255, 153, 0));
        step4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel4.setText("Step4");
        step4.add(jLabel4);
        jLabel4.setBounds(12, 13, 64, 29);

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel28.setText("Enter the changing Vitamins");
        step4.add(jLabel28);
        jLabel28.setBounds(270, 20, 320, 29);

        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        step4.add(jTextField19);
        jTextField19.setBounds(280, 100, 100, 22);
        step4.add(jTextField20);
        jTextField20.setBounds(280, 140, 100, 22);

        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        step4.add(jTextField21);
        jTextField21.setBounds(280, 180, 100, 22);
        step4.add(jTextField22);
        jTextField22.setBounds(280, 220, 100, 22);
        step4.add(jTextField23);
        jTextField23.setBounds(280, 260, 100, 22);
        step4.add(jTextField24);
        jTextField24.setBounds(280, 300, 100, 22);
        step4.add(jTextField25);
        jTextField25.setBounds(280, 340, 100, 22);
        step4.add(jTextField26);
        jTextField26.setBounds(580, 100, 100, 22);
        step4.add(jTextField27);
        jTextField27.setBounds(580, 170, 100, 22);
        step4.add(jTextField28);
        jTextField28.setBounds(580, 140, 100, 22);
        step4.add(jTextField29);
        jTextField29.setBounds(580, 210, 100, 22);
        step4.add(jTextField30);
        jTextField30.setBounds(580, 260, 100, 22);

        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });
        step4.add(jTextField31);
        jTextField31.setBounds(580, 300, 100, 22);

        jLabel29.setText("Vitamin_A ");
        step4.add(jLabel29);
        jLabel29.setBounds(190, 100, 62, 16);

        jLabel30.setText("Thiamin");
        step4.add(jLabel30);
        jLabel30.setBounds(190, 140, 46, 16);

        jLabel31.setText("Ribloflevin ");
        step4.add(jLabel31);
        jLabel31.setBounds(190, 190, 62, 16);

        jLabel32.setText("niacin");
        step4.add(jLabel32);
        jLabel32.setBounds(190, 220, 33, 16);

        jLabel33.setText("pantothenic");
        step4.add(jLabel33);
        jLabel33.setBounds(190, 260, 66, 16);

        jLabel34.setText("biotin ");
        step4.add(jLabel34);
        jLabel34.setBounds(190, 300, 35, 16);

        jLabel35.setText("piridoxine");
        step4.add(jLabel35);
        jLabel35.setBounds(190, 340, 55, 16);

        jLabel36.setText("vitamin_B12");
        step4.add(jLabel36);
        jLabel36.setBounds(480, 100, 69, 16);

        jLabel37.setText("folic_acid");
        step4.add(jLabel37);
        jLabel37.setBounds(480, 140, 53, 16);

        jLabel38.setText("Vitamin_C");
        step4.add(jLabel38);
        jLabel38.setBounds(480, 170, 58, 16);

        jLabel39.setText("Vitamin_D");
        step4.add(jLabel39);
        jLabel39.setBounds(480, 210, 58, 16);

        jLabel40.setText("vitamin_E ");
        step4.add(jLabel40);
        jLabel40.setBounds(480, 260, 59, 16);

        jLabel41.setText("vitamin_k ");
        step4.add(jLabel41);
        jLabel41.setBounds(480, 300, 58, 16);

        jButton4.setText("OK");
        jButton4.setBorder(new javax.swing.border.MatteBorder(null));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        step4.add(jButton4);
        jButton4.setBounds(540, 400, 220, 60);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/change_items/bg_3.jpg"))); // NOI18N
        step4.add(jLabel45);
        jLabel45.setBounds(-830, -380, 1650, 960);

        parent_panal_change.add(step4, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(parent_panal_change, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(parent_panal_change, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String catogary= (String)jComboBox1.getSelectedItem();
  
       if(catogary=="Rice category"){ rs = find_r(jTextField2.getText());   
         try{
            if(rs.next()){
              what=1;
                movingpanals();
               }
            else{
               
                 JOptionPane.showMessageDialog(null, " This ID is not available");
            }
         
         
         }
       catch(Exception ex){}
       
       
       }
      if(catogary=="Vegitabale category"){rs1 = find_v(jTextField2.getText());
        
         try{
            if(rs1.next()){
              what=2;
                movingpanals();
                }
            else{ JOptionPane.showMessageDialog(null, " This ID is not available");}
        
         
         }
       catch(Exception ex){}
      }
      if(catogary=="Meat & fish category"){rs2 = find_m(jTextField2.getText());
        
         try{
            if(rs2.next()){ 
            what=3;
             movingpanals();
               }
            else{
               JOptionPane.showMessageDialog(null, " This ID is not available");
               }
          
         
         }
       catch(Exception ex){}
      
      }
         if(catogary=="Dessert category"){rs3= find_d(jTextField2.getText());
           
         try{
            if(rs3.next()){ 
                what=4;
                movingpanals();
                }
            else{ JOptionPane.showMessageDialog(null, " This ID is not available");}
       
     
         }
       catch(Exception ex){}}
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String m1= jTextField1.getText(),m2=jTextField3.getText(),m3=jTextField4.getText(),m4=jTextField5.getText(),m5=jTextField6.getText()
                ,m6=jTextField7.getText(),m7=jTextField8.getText(),m8=jTextField9.getText(),m9=jTextField10.getText(),m10=jTextField11.getText(),
                m11=jTextField12.getText(),m12=jTextField13.getText(),m13=jTextField14.getText(),m14=jTextField15.getText();
           String id=  jTextField2.getText();       
          update_minarls(id,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14);
         movingpanals2();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String n1=jTextField16.getText(),n2=jTextField17.getText(),n3=jTextField18.getText();
         String id=  jTextField2.getText(); 
         System.out.println(id);
        update_nutrition(id,n1,n2,n3);
         movingpanals3();
        
        
         movingpanals3();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         String v1= jTextField19.getText(),v2=jTextField20.getText(),v3=jTextField21.getText(),v4=jTextField22.getText(),v5=jTextField23.getText()
                ,v6=jTextField24.getText(),v7=jTextField25.getText(),v8=jTextField26.getText(),v9=jTextField27.getText(),v10=jTextField28.getText(),
                v11=jTextField29.getText(),v12=jTextField30.getText(),v13=jTextField31.getText();
           String id=  jTextField2.getText();       
          update_vitamin(id,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13);
          JOptionPane.showMessageDialog(rootPane, "You update  sussfully!   item id :"+jTextField2.getText()+"");
                                            
           String[] args = null;
     selection.selectionmain(args);
     close();
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void changemain(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new change().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel parent_panal_change;
    private javax.swing.JPanel step1;
    private javax.swing.JPanel step2;
    private javax.swing.JPanel step3;
    private javax.swing.JPanel step4;
    // End of variables declaration//GEN-END:variables

    
    
     ResultSet rs = null;
    ResultSet rs1 = null;
         ResultSet rs2 = null;
          ResultSet rs3 = null;
PreparedStatement ps = null;
    
 public ResultSet find_r(String s){
      
           try{ 
          conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/online_food_order","root","");
           ps = (PreparedStatement) conn.prepareStatement("select * from rice_varieties where RiceId = ?");
           ps.setString(1,s);
           rs = ps.executeQuery();
           }catch(SQLException ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
           }
           return rs;

       }
  public ResultSet find_v(String s){
           try{
          conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/online_food_order","root","");
           ps = (PreparedStatement) conn.prepareStatement("select * from vegetables where VegetableId = ?");
           ps.setString(1,s);
           rs1 = ps.executeQuery();
           }catch(SQLException ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
           }
           return rs1;

       }
  public ResultSet find_m(String s){
           try{
          conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/online_food_order","root","");
           ps = (PreparedStatement) conn.prepareStatement("select * from meat_and_fish where Meat_or_FishId = ?");
           ps.setString(1,s);
           rs2= ps.executeQuery();
           }catch(Exception ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
           }
           return rs2;

       }
  public ResultSet find_d(String s){
           try{
          conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/online_food_order","root","");
           ps = (PreparedStatement) conn.prepareStatement("select * from dessert where DessertId = ?");
           ps.setString(1,s);
           rs3 = ps.executeQuery();
           }catch(Exception ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
           }
           return rs3;

       }

public void movingpanals(){
    parent_panal_change.removeAll();
       parent_panal_change.add(step2);
       parent_panal_change.repaint();
       parent_panal_change.revalidate();
      } 



public void movingpanals2(){
   parent_panal_change.removeAll();
       parent_panal_change.add(step3);
       parent_panal_change.repaint();
       parent_panal_change.revalidate();
       
      }   
public void movingpanals3(){
   parent_panal_change.removeAll();
       parent_panal_change.add(step4);
       parent_panal_change.repaint();
       parent_panal_change.revalidate();
      }   





public void update_minarls(String id,String m1,String m2,String m3,String m4,String m5,String m6,String m7,String m8,String m9,String m10,String m11,String m12,String m13,String m14){
    try {
    String sq5 = null;
    if(what==1){ sq5="UPDATE `content_minarals_for_rice` SET `calcium`=?,`chloride`=?,`chromium`=?,`copper`=?,`fluoride`=?,`Iodine`=?,`iron`=?,`magnesium`=?,`molybdenum`=?,`phosphorus`=?,`potassium`=?,`selenium`=?,`znc`=?,`sodium`=? WHERE RiceId =?";}
  if(what==2){ sq5="UPDATE `content_minarals_for_vegetables` SET `calcium`=?,`chloride`=?,`chromium`=?,`copper`=?,`fluoride`=?,`Iodine`=?,`iron`=?,`magnesium`=?,`molybdenum`=?,`phosphorus`=?,`potassium`=?,`selenium`=?,`znc`=?,`sodium`=? WHERE vegetableId =?";}
  if(what==3){ sq5="UPDATE `content_minarals_for_meat_and_fish` SET `calcium`=?,`chloride`=?,`chromium`=?,`copper`=?,`fluoride`=?,`Iodine`=?,`iron`=?,`magnesium`=?,`molybdenum`=?,`phosphorus`=?,`potassium`=?,`selenium`=?,`znc`=?,`sodium`=? WHERE meat_and_fishId =?";}
  if(what==4){ sq5="UPDATE `content_minarals_for_dessert` SET `calcium`=?,`chloride`=?,`chromium`=?,`copper`=?,`fluoride`=?,`Iodine`=?,`iron`=?,`magnesium`=?,`molybdenum`=?,`phosphorus`=?,`potassium`=?,`selenium`=?,`znc`=?,`sodium`=? WHERE dessertId =?";}
    
    conn2= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/online_food_order","root","");
           pre=(PreparedStatement) conn.prepareStatement(sq5);
           pre.setString(1, m1);
           pre.setString(2,m2);
           pre.setString(3, m3);
           pre.setString(4,m4);
           pre.setString(5, m5);
           pre.setString(6,m6);
           pre.setString(7, m7);
           pre.setString(8,m8);
           pre.setString(9, m9);
           pre.setString(10,m10);
           pre.setString(11, m11);
           pre.setString(12,m12);
           pre.setString(13, m13);
           pre.setString(14, m14);
           pre.setString(15,id);
           pre.executeUpdate();
    
    
    
    } catch(Exception ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
        }
 }
public void update_nutrition(String id,String n1,String n2,String n3){
  try {String sq4=null;
    if(what==1){   sq4="UPDATE `content_nutrition_for_rice` SET `protien`=?,`carbohydrate`=?,`fat`=? WHERE `RiceId`=?";}
    if(what==2){  sq4="UPDATE `content_nutrition_for_vegetables` SET `protien`=?,`carbohydrate`=?,`fat`=? WHERE `vegitableId`=?";}
    if(what==3){   sq4="UPDATE `content_nutrition_for_meat_and_fish` SET `protien`=?,`carbohydrate`=?,`fat`=? WHERE `meat_and_fishId`=?";}
    if(what==4){   sq4="UPDATE `content_nutrition_for_dessert SET `protien`=?,`carbohydrate`=?,`fat`=? WHERE `dessertId`=?";}
      pre=(PreparedStatement) conn.prepareStatement(sq4);
      
          
           pre.setString(1, n1);
            pre.setString(2,n2);
           pre.setString(3, n3);
           pre.setString(4,id);
          pre.executeUpdate();
      
      
  }catch(Exception ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
        }
  }
  public void update_vitamin(String id,String v1,String v2,String v3,String v4,String v5,String v6,String v7,String v8,String v9,String v10,String v11,String v12,String v13){
  try {
     
      String sq4=null;
      if(what==1){ sq4="UPDATE content_vitamins_in_rice SET`Vitamin_A`=?,`Thiamin`=?,`Ribloflevin`=?,`niacin`=?,`pantothenic`=?,`biotin`=?,`piridoxine`=?,`vitamin_B12`=?,`folic_acid`=?,`Vitamin_C`=?,`Vitamin_D`=?,`vitamin_E`=?,`vitamin_k`=? WHERE `RiceId`=?";}
      if(what==2){sq4="UPDATE `content_vitamins_in_vegetables` SET`Vitamin_A`=?,`Thiamin`=?,`Ribloflevin`=?,`niacin`=?,`pantothenic`=?,`biotin`=?,`piridoxine`=?,`vitamin_B12`=?,`folic_acid`=?,`Vitamin_C`=?,`Vitamin_D`=?,`vitamin_E`=?,`vitamin_k`=? WHERE `vegetableId`=?";}
      if(what==3){sq4="UPDATE `content_vitamins_in_meat_and_fish` SET`Vitamin_A`=?,`Thiamin`=?,`Ribloflevin`=?,`niacin`=?,`pantothenic`=?,`biotin`=?,`piridoxine`=?,`vitamin_B12`=?,`folic_acid`=?,`Vitamin_C`=?,`Vitamin_D`=?,`vitamin_E`=?,`vitamin_k`=? WHERE `meat_and_fishId`=?";}
      if(what==4){sq4="UPDATE `content_vitamins_in_dessert` SET`Vitamin_A`=?,`Thiamin`=?,`Ribloflevin`=?,`niacin`=?,`pantothenic`=?,`biotin`=?,`piridoxine`=?,`vitamin_B12`=?,`folic_acid`=?,`Vitamin_C`=?,`Vitamin_D`=?,`vitamin_E`=?,`vitamin_k`=? WHERE `dessertId`=?";}
          
      
      pre=(PreparedStatement) conn.prepareStatement(sq4);
      
           pre.setString(1, v1);
            pre.setString(2,v2);
           pre.setString(3, v3);
           pre.setString(4, v4);
            pre.setString(5,v5);
           pre.setString(6, v6);
           pre.setString(7,v7);
           pre.setString(8, v8);
            pre.setString(9,v9);
           pre.setString(10, v10);
           pre.setString(11, v11);
            pre.setString(12,v12);
           pre.setString(13, v13);
            pre.setString(14,id);
          pre.executeUpdate();
      
      
  }catch(Exception ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
        }
  }


public  void close(){
WindowEvent windowClose= new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowClose);
}

}









